# Default values for admission-controller-ingress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
namespace: kube-system
image:
  repository: speriyasamy/k8s-ingress-admission-controller
  tag: latest
  pullPolicy: Always
service:
  name: k8s-ingress-admission-controller
  type: ClusterIP
  externalPort: 443
  internalPort: 8000
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi